# Generated by Django 3.1.2 on 2021-03-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='password2',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
    ]
