# Generated by Django 3.1.2 on 2021-03-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_admin_panel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_panel',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user_data',
            name='username',
            field=models.CharField(default=-1.0, max_length=30),
            preserve_default=False,
        ),
    ]
