# Generated by Django 3.1.2 on 2021-03-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_auto_20210301_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('address', models.TextField()),
                ('number', models.IntegerField()),
                ('prdouct_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.product')),
            ],
        ),
    ]
