# Generated by Django 3.1.2 on 2021-03-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_order_detail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
