# Generated by Django 3.1.2 on 2021-03-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_auto_20210301_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='productprice',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
    ]
