# Generated by Django 3.1.2 on 2021-03-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_auto_20210302_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='confirm_password',
            field=models.CharField(default=-1.0, max_length=30),
            preserve_default=False,
        ),
    ]
