# Generated by Django 3.1.2 on 2021-03-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_order_detail_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='confirm_password',
        ),
    ]
