# Generated by Django 3.1.2 on 2021-03-02 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0011_remove_order_detail_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='password',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='broker.user_data'),
            preserve_default=False,
        ),
    ]
